### ISSUE TITLE
installation broken for linux debian (Kali) 

### ISSUE THREAD

**Issue by zux0x3a** [fanoframework/fano-cli#10]
Hi trying to have a look into fano but unfortunately not able to install fano-cli due to some missing units on the src installation code, not sure where the error is located, as i already have FPC +3 installed + lazarus-IDE

```
Compiling ./src/Tasks/Implementations/Minifier/DirFileMinifierTaskImpl.pas
Writing Resource String Table file: DirFileMinifierTaskImpl.rsj
Compiling ./src/Libs/Minifier/Implementations/JsMinifierImpl.pas
Compiling ./src/Libs/Minifier/Contracts/MinifierIntf.pas
JsMinifierImpl.pas(18,5) Fatal: Can't find unit jsminifier used by JsMinifierImpl
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
```

**Comment by zamronypj** [comment]
@lawrenceamer  `jsminifier` unit is in Free Pascal built-in package fcl-js. Make sure you have FPC source path correctly in your PATH  environment variable https://gitlab.com/freepascal.org/fpc/source/-/blob/811c68377596fdebf8bfcee8e8ce773df42593f7/packages/fcl-js/src/jsminifier.pp

**Comment by zamronypj** [comment]
To be able to identified what directories that Free Pascal is trying to look for that file, you can edit file `build.dev.cfg` remove last lines from

```
#----------------------------------------------
# Verbose unit searching info,
# Remove comment, in case unit file is not found
# so Free Pascal will output verbose message where
# it tries to look for unit file
#----------------------------------------------
#-vut
```

to

```
#----------------------------------------------
# Verbose unit searching info,
# Remove comment, in case unit file is not found
# so Free Pascal will output verbose message where
# it tries to look for unit file
#----------------------------------------------
-vut
```

and then run `build.sh` with `BUILD_TYPE=dev`

```
$ BUILD_TYPE=dev ./build.sh
```

**Comment by zux0x3a** [comment]
i don't think my fpc is broken, rather than i still believe due to something missing in the compilation command, after doing build_type=dev i got all of no found search in unit something like 

/usr/lib/x86_64-linux-gnu/fpc/3.2.2/units .. etc

**Comment by zamronypj** [comment]
Do you have `jsminifier.pp` unit somewhere in your machine?

**Comment by zux0x3a** [comment]
it is found on the following path /home/kali/fpcupdeluxe/fpcsrc/packages/fcl-js/src/jsminifier.pp, since I am using fpcupdeluxe for my lazarus-ide, but I tried to direct my build through FPC_BIN=/home/kali/fpcupdeluxe/fpc/bin/x86_64-linux/fpc ./build.sh, but still same error!

**Comment by zamronypj** [comment]
also can you share the output where Free Pascal compiler looks for `jsminifier` unit

for example, mine,
```
Searching file bin/unit/jsminifier.o... not found
Searching file bin/unit/JSMINIFIER.O... not found
Searching file /home/zamroni/fpcupdeluxe/fpc/units/x86_64-linux/fcl-js/jsminifier.o... found
```

**Comment by zux0x3a** [comment]
it displays the following error 
```
hom/kali/fpcupdeluxe/fpc/bin/x86_64-linux/jsminifi.pp... not found
Searching file /home/kali/fpcupdeluxe/fpc/bin/x86_64-linux/JSMINIFI.PP... not found
```
it should be looking into fpcupdeluxe/fpcsrc/packages/fcl-js/ folder while it doesn't

**Comment by zux0x3a** [comment]
sorry i mean it should look for inside 
/home/kali/fpcupdeluxe/fpc/units/x86_64-linux but it is not doing that

**Comment by zamronypj** [comment]
you may want to inspect content of `/etc/fpc.cfg` as I believe Free Pascal will also looks for directories to search.

**Comment by zamronypj** [comment]
my `/etc/fpc.cfg` also contains

```
# searchpath for units and other system dependent things
-Fu/home/zamroni/fpcupdeluxe/fpc/units/$fpctarget
-Fu/home/zamroni/fpcupdeluxe/fpc/units/$fpctarget/*
-Fu/home/zamroni/fpcupdeluxe/fpc/units/$fpctarget/rtl
```

which i believe was set when I installed fpcupdeluxe.

**Comment by zux0x3a** [comment]
yeah, i confirm I have the same values, but the fpc.cfg is inside the fpcupdeluxe folder not /etc/ folder

**Comment by zamronypj** [comment]
can you symlink fpcdeluxe fpc.cfg into `/etc/fpc.cfg`?

**Comment by zamronypj** [comment]
https://fanoframework.github.io/known-issues/#missing-etc-fpc-cfg

**Comment by zux0x3a** [comment]
cool now it is working, it was referring to /etc/fpc.cfg, while that not symlinked to fpcupdelux dir.

**Comment by zamronypj** [comment]
nice. close this issue now
