### ISSUE TITLE
Fano CLI won't compile on Windows 10

### ISSUE THREAD

**Issue by cwchentw** [fanoframework/fano-cli#3]
After tweaking *build.cfg*, I could invoke Free Pascal to compile Fano CLI.

Nevertheless, `fpc` failed to compile Fano CLI because Fano CLI depends on some Unix specific code. To my knowledge, here are affected sources:

* ApacheEnableVhostTaskImpl.pas
* BasicKeyGeneratorImpl.pas
* RootCheckTaskImpl.pas

It seems the code in these sources are Unix specific, no equivalent Windows one. Consider to skip those source when compiling Fano CLI on Windows.

**Comment by zamronypj** [comment]
Thank you for your feedback. Fano Framework is not yet supported in Windows. The workaround maybe is to run linux inside docker when using Windows.

**Comment by zamronypj** [comment]
Fixed in v1.10.0 1bc8f3b4959
